// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.680
package component

import (
	"context"
	"fmt"
	"html"
	"io"

	"github.com/a-h/templ"
	"github.com/softsrv/steamapi/steamapi"
)

func Navbar(player steamapi.Player, username string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
		_, err := io.WriteString(w, `<div class="navbar bg-base-100"><div class="flex-1"><a class="btn btn-ghost text-xl" href="/">Gather Your Party</a></div><div class="flex-none"><ul class="menu menu-horizontal px-1">`)
		if err != nil {
			return err
		}
		if player.PersonaName != "" {
			_, err = fmt.Fprintf(w, `<li><details><summary><img src="%s"> %s</summary><ul class="p-2 bg-base-100 rounded-t-none"><li><a>profile</a></li><li><a>log out</a></li></ul></details></li>`, html.EscapeString(player.AvatarSmall), html.EscapeString(player.PersonaName))
		} else {
			_, err = io.WriteString(w, `<li><a href="/login">Login</a></li>`)
		}
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, `</ul></div></div>`)
		return err
	})
}

func Banner() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
		_, err := io.WriteString(w, `<header class="p-6 flex flex-col justify-between"><img src="/static/svg/logo.svg" class="h-20 w-20"></header>`)
		return err
	})
}

func Main() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
		_, err := io.WriteString(w, `<div class="mb-4"><div id="game-list"><button hx-target="#game-list" hx-get="/frag/games" class="btn btn-active btn-primary w-full flex justify-center text-gray-100 p-3  rounded-full tracking-wide font-semibold  shadow-lg cursor-pointer transition ease-in duration-200">Show Games</button> <button hx-target="#game-list" hx-get="/frag/friends" class="btn btn-active btn-primary w-full flex justify-center text-gray-100 p-3  rounded-full tracking-wide font-semibold  shadow-lg cursor-pointer transition ease-in duration-200">Show Friends</button></div></div>`)
		return err
	})
}

func TextAndTitle(title string, text string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
		_, err := fmt.Fprintf(w, `<div><h1 class="text-lg font-bold">%s</h1><p class="text-sm">%s</p></div>`, html.EscapeString(title), html.EscapeString(text))
		return err
	})
}

func ErrorMessage(msg string) templ.Component {
	return ErrorMessages([]string{msg})
}

func ErrorMessages(msgs []string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
		if _, err := io.WriteString(w, `<div class="alert alert-error text-error-content" role="alert"><ul>`); err != nil {
			return err
		}
		for _, msg := range msgs {
			if _, err := fmt.Fprintf(w, `<li>%s</li>`, html.EscapeString(msg)); err != nil {
				return err
			}
		}
		_, err := io.WriteString(w, `</ul></div>`)
		return err
	})
}

func Signin() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
		_, err := io.WriteString(w, `<div class="min-h-screen sm:flex sm:flex-row mx-0 justify-center"><div class="flex-col flex  self-center p-10 sm:max-w-5xl xl:max-w-2xl  z-10"><div class="self-start hidden lg:flex flex-col  text-white"><h1 class="mb-3 font-bold text-5xl">Gather Your Party </h1><p class="pr-3">log in here</p></div></div><div class="flex justify-center self-center  z-10"><div class="p-12 bg-white mx-auto rounded-2xl w-100 "><div class="mb-4"><h3 class="font-semibold text-2xl text-gray-800">Sign In </h3><p class="text-gray-500">Please provide your steam ID. You can find this on your Steam account profile page.</p></div><div class="space-y-5"><form id="login" hx-post="/login"><div class="mb-4"><div class="space-y-2"><label class="mb-5 text-sm font-medium text-gray-700 tracking-wide">SteamID</label> <input name="steamID" class="w-full content-center text-base px-4 py-2 border  border-gray-300 rounded-lg focus:outline-none focus:border-green-400" placeholder="Enter your SteamID"></div></div><div class="mb-4"><div><button type="submit" class="btn btn-active btn-primary w-full flex justify-center text-gray-100 p-3  rounded-full tracking-wide font-semibold  shadow-lg cursor-pointer transition ease-in duration-200">Sign in</button></div></div></form></div><div class="pt-5 text-center text-gray-400 text-xs"><span>Copyright © 2021-2022 <a href="https://codepen.io/uidesignhub" rel="" target="_blank" title="Ajimon" class="text-green hover:text-green-500 ">AJI</a></span></div></div></div></div>`)
		return err
	})
}
